find_package(BLAS QUIET)

if(BLAS_FOUND)
    #message(STATUS "[X]   BLAS was found: |${OPENBLAS_VERSION}|")
    if (OPENBLAS_VERSION STREQUAL "")
        message(STATUS "[X]   BLAS was found: ${OPENBLAS_VERSION}")
    else ()
        pkg_check_modules(BLAS_PKG QUIET blas)
        if(BLAS_PKG_FOUND)
            message(STATUS "[X]   BLAS version: ${BLAS_PKG_VERSION}")
        endif ()
    endif ()

    #message(STATUS ${BLAS_LIBRARIES})
    # target_compile_definitions(${PROJECT_NAME} PRIVATE -DUSE_BLAS=1)
    # list(APPEND ${LINK_LIBRARIES} ${BLAS_LIBRARIES})
    add_definitions(-DUSE_BLAS=1)
else ()
    message(STATUS "[ ]   BLAS was not found")
endif ()